### ISSUE TITLE
Debian 8 - VMware enviroment is not correctly detected

### ISSUE THREAD

**Issue by it-praktyk** [geerlingguy/packer-debian-8#1]
The current test for run Debian 8 in VMware environment use

```
$ cat /proc/scsi/scsi
```
but for Debian 8.8 (I'm preparing update to this version) the result is

```
cat: /proc/scsi/scsi: No such file or directory
```

The better option is to use 

```
$ dmesg | grep VMware | wc -l
5
```

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/packer-debian-8/issues/4
